### ISSUE TITLE
Alignment issue @Conversation History Table Header.

### ISSUE THREAD

**Issue by Jayasimman** [Sundar-Infographic-Analytics/chatRep#10]

**Comment by Jayasimman** [comment]
Same issue in Time Column.

**Comment by Jayasimman** [comment]
![image](https://user-images.githubusercontent.com/68588689/106586218-2ebedb80-656e-11eb-9cd1-29ff2c4a2746.png)

**Comment by Jayasimman** [comment]
In time column

**Comment by jayashreejaya** [comment]
issue resolved
