### ISSUE TITLE
Checkbox design in Assign chat @Dashboard

### ISSUE THREAD

**Issue by Jayasimman** [Sundar-Infographic-Analytics/chatRep#17]

**Comment by jayashreejaya** [comment]
can you please add ss for this issue.

**Comment by Jayasimman** [comment]
![image](https://user-images.githubusercontent.com/68588689/106601339-8adf2b00-6581-11eb-9d40-c8fc9babd7c3.png)

**Comment by jayashreejaya** [comment]
issue resolved
