### ISSUE TITLE
@Pagination alignment issue @Dashboard

### ISSUE THREAD

**Issue by Jayasimman** [Sundar-Infographic-Analytics/chatRep#4]

**Comment by jayashreejaya** [comment]
I cannot find alignment issue in my monitor, please add the ss of this issue.

**Comment by Jayasimman** [comment]
![image](https://user-images.githubusercontent.com/68588689/106586614-b278c800-656e-11eb-8d24-0325dde5e17f.png)
Need Pagination

**Comment by jayashreejaya** [comment]
issue resolved
