### ISSUE TITLE
Table header alignment @Assigned to me

### ISSUE THREAD

**Issue by Jayasimman** [Sundar-Infographic-Analytics/chatRep#8]

**Comment by jayashreejaya** [comment]
can you please add ss for this issue

**Comment by Jayasimman** [comment]
![image](https://user-images.githubusercontent.com/68588689/106586479-83faed00-656e-11eb-9800-6a1e49579387.png)

**Comment by Jayasimman** [comment]
Change status

**Comment by jayashreejaya** [comment]
issue resolved
